version: "3"

networks:
  meleenet:
    driver: bridge

volumes:
  db-data:

services:
  webservice:
    build:
      context: ./webservice
      dockerfile: Dockerfile
    image: melee-v2-webservice:1.0.0
    container_name: melee-v2-webservice
    restart: unless-stopped
    env_file: .env
    volumes: 
      - ./webservice:/usr/src/app
    ports:
      - 8000:8000
    command: npm run start
    depends_on:
      - db
    links:
      - db
    networks:
      - meleenet

  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    image: melee-v2-website:1.0.0
    container_name: melee-v2-website
    restart: unless-stopped
    volumes: 
      - ./website:/usr/src/app
    ports:
      - 8080:8000
    command: npm run start
  
  db:
    image: mongo
    container_name: melee-v2-db
    restart: always
    env_file: .env
    volumes:
      - db-data:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    ports:
      - 27017:27017
    networks:
      - meleenet
  
  db-client:
    image: mongo-express
    container_name: melee-v2-db-gui
    restart: always
    env_file: .env
    depends_on:
      - db
    ports:
      - "8081:8081"
    networks:
      - meleenet